config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # devise_for :users
  get 'up' => 'rails/health#show', as: :rails_health_check
  # Ways to define a route
  # get 'home/index'
  # get '/home' => 'home#index'
  # defining a root page
  root 'home#index'

  resources :employees
  resources :documents

  devise_for :users

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  # public pages routes
  get 'about' => 'pages#about_us'
  get 'contact' => 'pages#contact_us'
  get 'privacy-policy' => 'pages#privacy_policy'
  get 'terms-and-conditions' => 'pages#terms_and_conditions'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/document.rb
class Document < ApplicationRecord

  DOC_TYPES = ['Marksheet', 'Photo ID', 'Address Proof', 'Personal ID', 'Others'].freeze

  belongs_to :employee

  has_one_attached :image

  validates :name, :doc_type, presence: true
end

app/models/employee.rb
class Employee < ApplicationRecord
  # Association Needs to be defined Manually after migrating the db mutation
  has_many :documents

  validates :first_name, :last_name, presence: true
  validates :personal_email, presence: true, uniqueness: true
  validates :city, :state, :country, :pincode, :address_line_1, presence: true

  def name
    "#{first_name} #{last_name}".strip
  end

  def full_address
    "#{address_line_1} #{address_line_2} #{city}, #{state}, #{country}, #{pincode}".strip
  end

  def name_with_email
    "#{name}(#{personal_email})"
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable, :trackable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Singing is required to access the site
  before_action :authenticate_user!
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :set_document, only: [:edit, :update, :show, :destroy]

  def index
    @documents = Document.all
  end

  def new
    @document = Document.new
  end

  def create
    @document = Document.new(document_params)
    if @document.save
      redirect_to documents_path, notice: 'Document Added...'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @document.update(document_params)
      redirect_to documents_path, notice: 'Document Updated...'
    else
      render :edit
    end
  end

  def show
  end

  def destroy
    if @document.destroy
      redirect_to documents_path, notice: 'Document Deleted...'
    end
  end

  private
  def document_params
    params.require(:document).permit(:name, :doc_type, :employee_id, :image)
  end

  def set_document
    @document = Document.find(params[:id])
  rescue ActiveRecord::RecordNotFound => error
    redirect_to documents_path, notice: error
  end

end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
	# Before Action filter
	before_action :set_employee, only: [:edit, :update, :show, :destroy]
	def index
		@employees = Employee.all
	end

	def new
		@employee = Employee.new
	end

	def create
		# Bad way to save values from param in the db
		# @employee = Employee.create(first_name: params[:employee][:first_name], middle_name: params[:employee][:middle_name], last_name: params[:employee][:last_name], personal_email: params[:employee][:personal_email], city: params[:employee][:city], state: params[:employee][:state], country: params[:employee][:country], pincode: params[:employee][:pincode], address_line_1: params[:employee][:address_line_1], address_line_2: params[:employee][:address_line_2])
		# Correct way
		@employee = Employee.new(employee_params)
		if @employee.save
			redirect_to employees_path, notice: 'Employee added successfully...'
		else
			render :new
		end
	end

	def edit
	end

	def update
		if @employee.update(employee_params)
			redirect_to employees_path, notice: 'Employee updated successfully...'
		else
			render :edit
		end
	end

	def show
	end

	def destroy
		if @employee.destroy
			redirect_to employees_path, notice: 'Employed deleted successfully...'
		end
	end

	# Method to permit params
	private
	def employee_params
		# Syntax to permit all the params but its not good practice to do it cos if you a customised input then you would get and error
		# params.require(:employee).permit!
		# Correct Way to permit params using strong parameters n not allowing any forbidden ones
		params.require(:employee).permit(:first_name, :middle_name, :last_name, :date_of_birth, :date_of_joining, :job_title, :personal_email, :about, :city, :state, :country, :pincode, :address_line_1, :address_line_2)
	end

	def set_employee
		@employee = Employee.find(params[:id])
	# Handling Exception if any record is not found
	rescue ActiveRecord::RecordNotFound => error
		redirect_to employees_path, notice: error
	end

end

app/controllers/home_controller.rb
# frozen_string_literal: true

# Home page of the Application
class HomeController < ApplicationController
  def index
    @page_title = 'Hello World!'
    @page_description = 'I am learning Rails!'
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about_us
  end

  def contact_us
  end

  def privacy_policy
  end

  def terms_and_conditions
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/documents/_form.html.erb
<%= form_with model: document do |form| %>
    <div class="row">
        <div class="col-lg-4">
            <div class="form-group mb-3 ">
                <%= form.label :name, class: 'mb-2' %>
                <%= form.text_field :name, class: 'form-control form-control-lg' %>
                <% document.errors.full_messages_for(:name).each do |error| %>
                    <p class="text-danger small"><%= error %></p>
                <% end %>
            </div>
            <div class="form-group mb-3 ">
                <%= form.label :doc_type, class: 'mb-2' %>
                <%= form.select :doc_type, options_for_select(Document::DOC_TYPES, selected: document.doc_type), {prompt: 'Select document type'}, class: 'form-control form-control-lg ' %>
                <% document.errors.full_messages_for(:doc_type).each do |error| %>
                    <p class="text-danger small"><%= error %></p>
                <% end %>
            </div>
            <div class="form-group mb-3 ">
                <%= form.label :employee_id, class: 'mb-2' %>
                <%= form.select :employee_id, options_for_select(Employee.all.map{|employee| [employee.name_with_email, employee.id]}, selected: document.employee_id), {prompt: 'Select employee'}, class: 'form-control form-control-lg ' %>
                <!-- Showing all employees using pluck method and passing attributes -->
                <%#= form.select :employee_id, options_for_select(Employee.pluck(:first_name, :id), selected: document.employee_id), {prompt: 'Select employee'}, class: 'form-control form-control-lg ' %>
                <% document.errors.full_messages_for(:employee_id).each do |error| %>
                    <p class="text-danger small"><%= error %></p>
                <% end %>
            </div>
            <div class="form-group mb-3 ">
                <%= form.label :image, class: 'mb-2' %><br />
                <%= form.file_field :image %>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <%= form.submit class: 'btn btn-primary btn-lg' %>
            <%= link_to 'Back to Documents', documents_path, class: 'btn btn-outline-primary btn-lg' %>
        </div>
    </div>
<% end %>

app/views/documents/edit.html.erb
<div class="col-lg-12">
	<h2 class="text-center mt-4 mb-4 font-weight-bold text-uppercase">Edit existing document information</h2>
    <!-- Form Start -->
    <%= render 'form', document: @document %>
    <!-- Form Ends -->
</div>

app/views/documents/index.html.erb
<div class="col-lg-12">
	<div class="font-weight-bold mt-2 text-center text-primary">
		<%= flash[:notice] %>
	</div>
	<h2 class="text-center mt-4 mb-4 font-weight-bold text-uppercase">
		Employees documents List
	</h2>
	<%# Link to new document template %>
	<div>
		<%= link_to 'Create new document', new_document_path, class: 'btn
		btn-primary btn-lg mb-4' %>
	</div>
	<table class="table table-bordered">
		<thead>
			<tr>
				<th>Name</th>
				<th>Doc type</th>
				<th>Employee</th>
				<th>Actions</th>
			</tr>
		</thead>
		<tbody>
			<% @documents.each do |document| %>
			<tr>
				<td><%= document.name %></td>
				<td><%= document.doc_type %></td>
				<td><%= link_to document.employee.name, employee_path(document.employee) %></td>
				<td>
					<div class="dropdown">
						<button
							class="btn btn-primary dropdown-toggle"
							type="button"
							data-bs-toggle="dropdown"
							aria-expanded="false"
						>
							Actions
						</button>
						<ul class="dropdown-menu">
							<li>
								<%= link_to 'Edit', edit_document_path(document), class:
								'dropdown-item' %>
							</li>
							<li>
								<%= link_to 'View', document_path(document), class:
								'dropdown-item' %>
							</li>
							<li>
								<%= link_to 'Delete', document_path(document), class:
								'dropdown-item', method: :delete, data: { confirm: 'Are you
								sure?' } %>
							</li>
						</ul>
					</div>
				</td>
			</tr>
			<% end %>
		</tbody>
	</table>
</div>

app/views/documents/new.html.erb
<div class="col-lg-12">
	<h2 class="text-center mt-4 mb-4 font-weight-bold text-uppercase">Create New Document</h2>
	<!-- Form Start -->
    <%= render 'form', document: @document %>
    <!-- Form Ends -->
</div>

app/views/documents/show.html.erb
<div class="col-lg-12">
	<h2 class="text-center mt-4 mb-4 font-weight-bold text-uppercase">Document Information</h2>
	<div class="row">
		<div class="col-lg-6">
			<!-- Displaying image -->
			<% if @document.image.attached? %>
				<%= image_tag @document.image, class: 'img-fluid' %>
			<% end %>
			<p class="lead mb-1 " style="font-size: large;">
				<strong>Name: </strong>
				<span><%= @document.name %></span>
			</p>
			<p class="lead mb-1 " style="font-size: large;">
				<strong>Doc type: </strong>
				<span><%= @document.doc_type %></span>
			</p>
			<p class="lead mb-1 " style="font-size: large;">
				<strong>Employee: </strong>
				<span><%= @document.employee.name %></span>
			</p>
		</div>
		<div class="col-lg-12">
			<%= link_to 'Back to documents', documents_path, class: "btn btn-outline-primary" %>
			<%= link_to 'Edit document', edit_document_path(@document), class: "btn btn-primary" %>
		</div>
	</div>
</div>

app/views/employees/_form.html.erb
<div>
    <%# Form %>
    <%= form_with model: employee do |form|  %>
        <!-- Showing all errors above the form -->
        <% if @employee.errors.any? %>
        <!-- <div class="row">
            <div class="col-lg-12">
                <h6>Please fix the following errors: </h6>
                <ul class="bg-light py-2 ">
                    <% @employee.errors.full_messages.each do |error| %>
                    <li class="text-danger"><%= error %></li>
                    <% end %>
                </ul>
            </div>
        </div> -->
        <% end %>
        <div class="row">
            <div class="col-lg-4">
                <div class="form-group mb-sm-4 mb-lg-4 ">
                    <%= form.label :first_name, class: 'mb-2' %>
                    <%= form.text_field :first_name, class: 'form-control form-control-lg' %>
                    <!-- Showing error below the field -->
                    <% @employee.errors.full_messages_for(:first_name).each do |error| %>
                    <p class="text-danger small"><%= error %></p>
                    <% end %>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="form-group mb-sm-4">
                    <%= form.label :middle_name, class: 'mb-2' %>
                    <%= form.text_field :middle_name, class: 'form-control form-control-lg' %>
                    <!-- Showing error below the field
                    <% @employee.errors.full_messages_for(:middle_name).each do |error| %>
                    <p class="text-danger small"><%= error %></p>
                    <% end %> -->
                </div>
            </div>
            <div class="col-lg-4">
                <div class="form-group mb-sm-4">
                    <%= form.label :last_name, class: 'mb-2' %>
                    <%= form.text_field :last_name, class: 'form-control form-control-lg' %>
                    <!-- Showing error below the field -->
                    <% @employee.errors.full_messages_for(:last_name).each do |error| %>
                    <p class="text-danger small"><%= error %></p>
                    <% end %>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="form-group mb-sm-4 mb-lg-4 ">
                    <%= form.label :date_of_birth, class: 'mb-2' %>
                    <%= form.date_field :date_of_birth, class: 'form-control form-control-lg' %>
                    <!-- Showing error below the field -->
                    <% @employee.errors.full_messages_for(:date_of_birth).each do |error| %>
                    <p class="text-danger small"><%= error %></p>
                    <% end %>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="form-group mb-sm-4">
                    <%= form.label :date_of_joining, class: 'mb-2' %>
                    <%= form.date_field :date_of_joining, class: 'form-control form-control-lg' %>
                    <!-- Showing error below the field -->
                    <% @employee.errors.full_messages_for(:date_of_joining).each do |error| %>
                    <p class="text-danger small"><%= error %></p>
                    <% end %>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="form-group mb-sm-4">
                    <%= form.label :job_title, class: 'mb-2' %>
                    <%= form.text_field :job_title, class: 'form-control form-control-lg' %>
                    <!-- Showing error below the field -->
                    <% @employee.errors.full_messages_for(:job_title).each do |error| %>
                    <p class="text-danger small"><%= error %></p>
                    <% end %>
                </div>
            </div>
            <div class="col-lg-12">
                <div class="form-group mb-sm-4 mb-lg-4 ">
                    <%= form.label :personal_email, class: 'mb-2' %>
                    <%= form.email_field :personal_email, class: 'form-control form-control-lg' %>
                    <!-- Showing error below the field -->
                    <% @employee.errors.full_messages_for(:personal_email).each do |error| %>
                    <p class="text-danger small"><%= error %></p>
                    <% end %>
                </div>
            </div>
            <div class="col-lg-12">
                <div class="form-group mb-sm-4 mb-lg-4 ">
                    <%= form.label :about, class: 'mb-2' %>
                    <%= form.text_area :about, class: 'form-control form-control-lg', rows: '5', style: 'resize: none' %>
                    <!-- Showing error below the field -->
                    <% @employee.errors.full_messages_for(:about).each do |error| %>
                    <p class="text-danger small"><%= error %></p>
                    <% end %>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-6 mb-lg-4 ">
                <div class="form-group mb-sm-4">
                    <%= form.label :address_line_1, class: 'mb-2' %>
                    <%= form.text_field :address_line_1, class: 'form-control form-control-lg' %>
                    <!-- Showing error below the field -->
                    <% @employee.errors.full_messages_for(:address_line_1).each do |error| %>
                    <p class="text-danger small"><%= error %></p>
                    <% end %>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="form-group mb-sm-4">
                    <%= form.label :address_line_2, class: 'mb-2' %>
                    <%= form.text_field :address_line_2, class: 'form-control form-control-lg' %>
                    <!-- Showing error below the field -->
                    <!-- <% @employee.errors.full_messages_for(:address_line_2).each do |error| %>
                    <p class="text-danger small"><%= error %></p>
                    <% end %> -->
                </div>
            </div>
            <div class="col-lg-3">
                <div class="form-group mb-sm-4">
                    <%= form.label :city, class: 'mb-2' %>
                    <%= form.text_field :city, class: 'form-control form-control-lg' %>
                    <!-- Showing error below the field -->
                    <% @employee.errors.full_messages_for(:city).each do |error| %>
                    <p class="text-danger small"><%= error %></p>
                    <% end %>
                </div>
            </div>
            <div class="col-lg-3">
                <div class="form-group mb-sm-4">
                    <%= form.label :state, class: 'mb-2' %>
                    <%= form.text_field :state, class: 'form-control form-control-lg' %>
                    <!-- Showing error below the field -->
                    <% @employee.errors.full_messages_for(:state).each do |error| %>
                    <p class="text-danger small"><%= error %></p>
                    <% end %>
                </div>
            </div>
            <div class="col-lg-3">
                <div class="form-group mb-sm-4">
                    <%= form.label :country, class: 'mb-2' %>
                    <%= form.text_field :country, class: 'form-control form-control-lg' %>
                    <!-- Showing error below the field -->
                    <% @employee.errors.full_messages_for(:country).each do |error| %>
                    <p class="text-danger small"><%= error %></p>
                    <% end %>
                </div>
            </div>
            <div class="col-lg-3">
                <div class="form-group mb-sm-4">
                    <%= form.label :pincode, class: 'mb-2' %>
                    <%= form.text_field :pincode, class: 'form-control form-control-lg' %>
                    <!-- Showing error below the field -->
                    <% @employee.errors.full_messages_for(:pincode).each do |error| %>
                    <p class="text-danger small"><%= error %></p>
                    <% end %>
                </div>
            </div>
        </div>
        <div class="row mt-lg-4  ">
            <div class="col-lg-12">
                <%= form.submit class: 'btn btn-primary btn-lg' %>
                <%= link_to 'Back to Employees', employees_path, class: 'btn btn-outline-primary btn-lg' %>
            </div>
        </div>
    <% end %>
</div>

app/views/employees/edit.html.erb
<div class="col-lg-12">
	<h2 class="text-center mt-4 mb-4 font-weight-bold text-uppercase">Update existing employee information</h2>
    <!-- Form Start -->
    <%= render 'form', employee: @employee %>
    <!-- Form Ends -->
</div>

app/views/employees/index.html.erb
<div class="col-lg-12">
	<div class="font-weight-bold mt-2 text-center text-primary">
		<%= flash[:notice] %>
	</div>
	<h2 class="text-center mt-4 mb-4 font-weight-bold text-uppercase">
		Employees List
	</h2>
	<%# Link to new employee template %>
	<div class="col-lg-6 mb-4">
		<%= link_to 'Create New Employee', new_employee_path, class: 'btn
		btn-primary btn-lg' %>
		<div class="dropdown d-inline-block ms-2">
			<button
				class="btn btn-primary btn-lg dropdown-toggle"
				type="button"
				data-bs-toggle="dropdown"
				aria-expanded="false"
			>
				View List in
			</button>
			<ul class="dropdown-menu">
				<li>
					<%= link_to 'Table', employees_path(view_type: 'table'), class:
					'dropdown-item' %>
				</li>
				<li>
					<%= link_to 'Accordion', employees_path(view_type: 'accordion'),
					class: 'dropdown-item' %>
				</li>
			</ul>
		</div>
	</div>
	<!-- Table View -->
	<% if params[:view_type] != 'accordion' %>
		<table class="table table-bordered">
			<thead>
				<tr>
					<th>Name</th>
					<th>Email</th>
					<th>Address</th>
					<th>Actions</th>
				</tr>
			</thead>
			<tbody>
				<% @employees.each do |employee| %>
				<tr>
					<td><%= employee.name %></td>
					<td><%= employee.personal_email %></td>
					<td><%= employee.full_address %></td>
					<td>
						<div class="dropdown">
							<button
								class="btn btn-primary dropdown-toggle"
								type="button"
								data-bs-toggle="dropdown"
								aria-expanded="false"
							>
								Actions
							</button>
							<ul class="dropdown-menu">
								<li>
									<%= link_to 'Edit', edit_employee_path(employee), class:
									'dropdown-item' %>
								</li>
								<li>
									<%= link_to 'View', employee_path(employee), class:
									'dropdown-item' %>
								</li>
								<li>
									<%= link_to 'Delete', employee_path(employee), class:
									'dropdown-item', method: :delete, data: { confirm: 'Are you
									sure?' } %>
								</li>
							</ul>
						</div>

						<!-- <%= link_to 'Edit', edit_employee_path(employee), class: 'btn btn-primary' %> -->
						<!-- <%= link_to 'View', employee_path(employee), class: 'btn btn-info' %> -->
						<!-- To make delete action work, 
						1. need to run './bin/importmap pin rails-ujs' command in the terminal
						2. import the package in application.js "import Rails from 'rails-ujs'" and "Rails.start()"  
						<%= link_to 'Delete', employee_path(employee), class: 'btn btn-danger', method: :delete, data: { confirm: 'Are you sure?' } %> 
					-->
					</td>
				</tr>
				<% end %>
			</tbody>
		</table>
	<% end %>
	<!-- Bootstrap Accordion View -->
	<% if params[:view_type].present? && params[:view_type] == 'accordion' %>
		<div class="accordion" id="accordionExample">
			<% @employees.each_with_index do |employee, index| %>
			<div class="accordion-item">
				<h2 class="accordion-header" id="heading_<%= index + 1 %>">
					<button
						class="accordion-button fs-5"
						type="button"
						data-bs-toggle="collapse"
						data-bs-target="#collapse_<%= index + 1 %>"
						aria-expanded="true"
						aria-controls="collapse_<%= index + 1 %>"
					>
						<%= employee.name_with_email %>
					</button>
				</h2>
				<div
					id="collapse_<%= index + 1 %>"
					class="accordion-collapse collapse"
					aria-labelledby="heading_<%= index + 1 %>"
					data-bs-parent="#accordionExample"
				>
					<div class="accordion-body">
						<div class="col-lg-12">
							<h2 class="text-center mt-4 mb-4 font-weight-bold text-uppercase">
								Employee Information
							</h2>
							<div class="row">
								<div class="col-lg-6">
									<h4 class="mb-2">
										<u>Personal details</u>
									</h4>
									<p class="lead mb-1" style="font-size: large">
										<strong>First Name: </strong>
										<span><%= employee.first_name %></span>
									</p>
									<p class="lead mb-1" style="font-size: large">
										<strong>Middle Name: </strong>
										<span
											><%= employee.middle_name.present? ? employee.middle_name :
											'N/A' %></span
										>
									</p>
									<p class="lead mb-1" style="font-size: large">
										<strong>Last Name: </strong>
										<span><%= employee.last_name %></span>
									</p>
									<p class="lead mb-1" style="font-size: large">
										<strong>Personal email: </strong>
										<span><%= employee.personal_email %></span>
									</p>
								</div>
								<div class="col-lg-6 mt-sm-4 ">
									<h4 class="mb-2">
										<u>Contact details</u>
									</h4>
									<p class="lead mb-1" style="font-size: large">
										<strong>Address Line 1: </strong>
										<span><%= employee.address_line_1 %></span>
									</p>
									<p class="lead mb-1" style="font-size: large">
										<strong>Address Line 2: </strong>
										<span
											><%= employee.address_line_2.present? ?
											employee.address_line_2 : 'N/A' %></span
										>
									</p>
									<p class="lead mb-1" style="font-size: large">
										<strong>City: </strong>
										<span><%= employee.city %></span>
									</p>
									<p class="lead mb-1" style="font-size: large">
										<strong>State: </strong>
										<span><%= employee.state %></span>
									</p>
									<p class="lead mb-1" style="font-size: large">
										<strong>Country: </strong>
										<span><%= employee.country %></span>
									</p>
									<p class="lead mb-1" style="font-size: large">
										<strong>Pincode: </strong>
										<span><%= employee.pincode %></span>
									</p>
								</div>
								<% if employee.documents.present? %>
								<div class="col-lg-12 mt-3">
									<h2 class="text-center font-weight-bold">Employee Documents</h2>
									<% employee.documents.each do |document| %>
									<div class="card">
										<div class="card-body">
											<div class="row">
												<% if document.image.attached? %>
												<div class="col-lg-4 mb-2">
													<%= image_tag document.image, class: 'img-fluid' %>
												</div>
												<% end %>
												<div class="col-lg-4">
													<%= document.name %> | <%= document.doc_type %>
												</div>
											</div>
										</div>
									</div>
									<% end %>
								</div>
								<% end %>
								<div class="col-lg-12 mt-4">
									<%= link_to 'Edit', edit_employee_path(employee), class: 'btn
									btn-primary' %> <%= link_to 'Delete', employee_path(employee),
									class: 'btn btn-danger', method: :delete, data: { confirm: 'Are
									you sure?' } %>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<% end %>
		</div>
	<% end %>
</div>

app/views/employees/show.html.erb
<div class="col-lg-12">
	<h2 class="text-center mt-4 mb-4 font-weight-bold text-uppercase">Employee Information</h2>
	<div class="row">
		<div class="col-lg-6">
			<h4 class=" mb-2">
				<u>Personal details</u>
			</h4>
			<p class="lead mb-1 " style="font-size: large;">
				<strong>First Name: </strong>
				<span><%= @employee.first_name %></span>
			</p>
			<p class="lead mb-1 " style="font-size: large;">
				<strong>Middle Name: </strong>
				<span><%= @employee.middle_name.present? ? @employee.middle_name : 'N/A' %></span>
			</p>
			<p class="lead mb-1 " style="font-size: large;">
				<strong>Last Name: </strong>
				<span><%= @employee.last_name %></span>
			</p>
			<p class="lead mb-1 " style="font-size: large;">
				<strong>Personal email: </strong>
				<span><%= @employee.personal_email %></span>
			</p>
		</div>
		<div class="col-lg-6 mt-sm-4">
			<h4 class=" mb-2">
				<u>Contact details</u>
			</h4>
			<p class="lead mb-1 " style="font-size: large;">
				<strong>Address Line 1: </strong>
				<span><%= @employee.address_line_1 %></span>
			</p>
			<p class="lead mb-1 " style="font-size: large;">
				<strong>Address Line 2: </strong>
				<span><%= @employee.address_line_2.present? ? @employee.address_line_2 : 'N/A' %></span>
			</p>
			<p class="lead mb-1 " style="font-size: large;">
				<strong>City: </strong>
				<span><%= @employee.city %></span>
			</p>
			<p class="lead mb-1 " style="font-size: large;">
				<strong>State: </strong>
				<span><%= @employee.state %></span>
			</p>
			<p class="lead mb-1 " style="font-size: large;">
				<strong>Country: </strong>
				<span><%= @employee.country %></span>
			</p>
			<p class="lead mb-1 " style="font-size: large;">
				<strong>Pincode: </strong>
				<span><%= @employee.pincode %></span>
			</p>
		</div>
		<% if @employee.documents.present? %>
			<div class="col-lg-12 mt-3 ">
				<h2 class="text-center font-weight-bold">Employee Documents</h2>
				<% @employee.documents.each do |document| %>
					<div class="card">
						<div class="card-body">
							<div class="row">
								<% if document.image.attached? %>
									<div class="col-lg-4 mb-2 ">
										<%= image_tag document.image, class: 'img-fluid' %>
									</div>
								<% end %>
								<div class="col-lg-4">
									<%= document.name %> | <%= document.doc_type %>
								</div>
							</div>
						</div>
					</div>
				<% end %>
			</div>
		<% end %>
		<div class="col-lg-12 mt-4 ">
			<%= link_to 'Back to employees', employees_path, class: "btn btn-outline-primary btn-lg" %>
			<%= link_to 'Edit employee', edit_employee_path(@employee), class: "btn btn-primary btn-lg" %>
		</div>
	</div>
</div>

app/views/home/index.html.erb
<div class="col-lg-10 mx-auto">
    
</div>

<%= render 'shared/links' %>

app/views/shared/_links.html.erb
<!-- Partials always start with underscore -->
<ul>
    <li><%= link_to 'About Us', about_path %></li>
    <li><%= link_to 'Contact Us', contact_path %></li>
    <li><%= link_to 'Privacy Policy', privacy_policy_path %></li>
    <li><%= link_to 'Terms and Condition', terms_and_conditions_path %></li>
</ul>
